language: python
os:
  - linux
python:
  - "3.6"
  - "3.5"
install:
  - make env.install
jobs:
  include:
    - stage: Deployment
      python: "3.6"
      script: make release.build
      deploy:
        provider: script
        script: echo "DONE"
        on:
          if: tag =~ /v\d+.\d+.\d+/
